### Define debug levels ###
/argoncube/analysis/stepsDebug 0

### Define verbosity levels ###
/argoncube/detector/optical/verbosity 1
#/tracking/verbose 1

### Load optical properties from JSON file ###
/argoncube/detector/optical/loadOptSett resources/OptSim.json

### Define volumes to kill photons ###
/argoncube/analysis/DefAbsVols volSiPM_Sens_PV volSiPM_LCM_PV

### Define volumes to detect photons ###
/argoncube/analysis/DefOptSD volSiPM_Sens_PV volSiPM_LCM_PV

### Define particle type and properties ###
/argoncube/gun/particle opticalphoton
#/argoncube/gun/polarization 0 1 0
#/argoncube/gun/angtype direction

### Define particle source ###
/argoncube/gun/sourceType Volume
/argoncube/gun/shape Box
/argoncube/gun/center -120.290000 -152.257091 -232.612500 mm
/argoncube/gun/halfx 25.227 mm
/argoncube/gun/halfy 28.679 mm
/argoncube/gun/halfz 25.846 mm

### Start visual interface ###
#/control/execute resources/macros/vis.mac

### Hit a SiPM in ArCLight ###
#/argoncube/gun/position 0 0 0
#/argoncube/gun/direction -2 -1.15 0

### Hit the TPB coating of ArCLight ###
#/argoncube/gun/position 0 -15 25 cm
#/argoncube/gun/direction 0 0.1 1

### Hit the TPB coating of LCM ###
#/argoncube/gun/position 0 15 25 cm
#/argoncube/gun/direction 0 0.1 1

#/argoncube/gun/position -135 22 -314.5 mm
/argoncube/gun/position 0 0 0
/argoncube/gun/primaryNb 1000
/run/beamOn 10000
